import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/component/hooks/context/AuthContext'
import FooterLinks from './footer-links'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-screen flex-col grow justify-between`}
      >
        <AuthProvider>{children}</AuthProvider>
        <footer className="flex flex-row justify-between items-center w-full bg-slate-200 py-2 px-4">
          <p>SpeedyMart</p>
          <section className="flex flex-row justify-around w-full bg-slate-200 py-2 px-4">
            <FooterLinks url={'/'} href={'/'} name={'Facebook'}  />
            <FooterLinks url={''} href={''} name={'Instagram'} />
            <FooterLinks url={''} href={''} name={'X'} />
            <FooterLinks url={''} href={''} name={'email'} />
            <FooterLinks url={''} href={''} name={'phone'} />
            <FooterLinks url={''} href={''} name={'tik-tok'} />
            <FooterLinks url={''} href={''} name={'snapchat'} />
          </section>
        </footer>
      </body>
    </html>
  )
}
